//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLiquidaciones.ProxyUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioBE", Namespace="http://schemas.datacontract.org/2004/07/LiquidacionServices.BE")]
    [System.SerializableAttribute()]
    public partial class UsuarioBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APELLIDOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CENTROGESTORIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CONTRASENAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PERFILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int USUARIOIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APELLIDOS {
            get {
                return this.APELLIDOSField;
            }
            set {
                if ((object.ReferenceEquals(this.APELLIDOSField, value) != true)) {
                    this.APELLIDOSField = value;
                    this.RaisePropertyChanged("APELLIDOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CENTROGESTORID {
            get {
                return this.CENTROGESTORIDField;
            }
            set {
                if ((this.CENTROGESTORIDField.Equals(value) != true)) {
                    this.CENTROGESTORIDField = value;
                    this.RaisePropertyChanged("CENTROGESTORID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CONTRASENA {
            get {
                return this.CONTRASENAField;
            }
            set {
                if ((object.ReferenceEquals(this.CONTRASENAField, value) != true)) {
                    this.CONTRASENAField = value;
                    this.RaisePropertyChanged("CONTRASENA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRES {
            get {
                return this.NOMBRESField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRESField, value) != true)) {
                    this.NOMBRESField = value;
                    this.RaisePropertyChanged("NOMBRES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PERFIL {
            get {
                return this.PERFILField;
            }
            set {
                if ((object.ReferenceEquals(this.PERFILField, value) != true)) {
                    this.PERFILField = value;
                    this.RaisePropertyChanged("PERFIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USUARIO {
            get {
                return this.USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOField, value) != true)) {
                    this.USUARIOField = value;
                    this.RaisePropertyChanged("USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int USUARIOID {
            get {
                return this.USUARIOIDField;
            }
            set {
                if ((this.USUARIOIDField.Equals(value) != true)) {
                    this.USUARIOIDField = value;
                    this.RaisePropertyChanged("USUARIOID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUsuario.IUsuarioSrv")]
    public interface IUsuarioSrv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioSrv/ObtenerUsuario", ReplyAction="http://tempuri.org/IUsuarioSrv/ObtenerUsuarioResponse")]
        SistemaLiquidaciones.ProxyUsuario.UsuarioBE ObtenerUsuario(string usuario, string contrasena);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioSrvChannel : SistemaLiquidaciones.ProxyUsuario.IUsuarioSrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioSrvClient : System.ServiceModel.ClientBase<SistemaLiquidaciones.ProxyUsuario.IUsuarioSrv>, SistemaLiquidaciones.ProxyUsuario.IUsuarioSrv {
        
        public UsuarioSrvClient() {
        }
        
        public UsuarioSrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioSrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioSrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SistemaLiquidaciones.ProxyUsuario.UsuarioBE ObtenerUsuario(string usuario, string contrasena) {
            return base.Channel.ObtenerUsuario(usuario, contrasena);
        }
    }
}
