//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLiquidaciones.ProxyPresupuesto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PresupuestoBE", Namespace="http://schemas.datacontract.org/2004/07/LiquidacionServices.BE")]
    [System.SerializableAttribute()]
    public partial class PresupuestoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ANHOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CENTROGESTORIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MONTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MONTODISPONIBLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PARTIDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PARTIDAIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PRESUPUESTOIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ANHO {
            get {
                return this.ANHOField;
            }
            set {
                if ((this.ANHOField.Equals(value) != true)) {
                    this.ANHOField = value;
                    this.RaisePropertyChanged("ANHO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CENTROGESTORID {
            get {
                return this.CENTROGESTORIDField;
            }
            set {
                if ((this.CENTROGESTORIDField.Equals(value) != true)) {
                    this.CENTROGESTORIDField = value;
                    this.RaisePropertyChanged("CENTROGESTORID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MES {
            get {
                return this.MESField;
            }
            set {
                if ((object.ReferenceEquals(this.MESField, value) != true)) {
                    this.MESField = value;
                    this.RaisePropertyChanged("MES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MONTO {
            get {
                return this.MONTOField;
            }
            set {
                if ((this.MONTOField.Equals(value) != true)) {
                    this.MONTOField = value;
                    this.RaisePropertyChanged("MONTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MONTODISPONIBLE {
            get {
                return this.MONTODISPONIBLEField;
            }
            set {
                if ((this.MONTODISPONIBLEField.Equals(value) != true)) {
                    this.MONTODISPONIBLEField = value;
                    this.RaisePropertyChanged("MONTODISPONIBLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PARTIDA {
            get {
                return this.PARTIDAField;
            }
            set {
                if ((object.ReferenceEquals(this.PARTIDAField, value) != true)) {
                    this.PARTIDAField = value;
                    this.RaisePropertyChanged("PARTIDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PARTIDAID {
            get {
                return this.PARTIDAIDField;
            }
            set {
                if ((this.PARTIDAIDField.Equals(value) != true)) {
                    this.PARTIDAIDField = value;
                    this.RaisePropertyChanged("PARTIDAID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PRESUPUESTOID {
            get {
                return this.PRESUPUESTOIDField;
            }
            set {
                if ((this.PRESUPUESTOIDField.Equals(value) != true)) {
                    this.PRESUPUESTOIDField = value;
                    this.RaisePropertyChanged("PRESUPUESTOID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyPresupuesto.IPresupuestoSrv")]
    public interface IPresupuestoSrv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPresupuestoSrv/ConsultarPresupuestoDispo", ReplyAction="http://tempuri.org/IPresupuestoSrv/ConsultarPresupuestoDispoResponse")]
        SistemaLiquidaciones.ProxyPresupuesto.PresupuestoBE[] ConsultarPresupuestoDispo(int CentroGestorId, int anho, string mes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPresupuestoSrvChannel : SistemaLiquidaciones.ProxyPresupuesto.IPresupuestoSrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PresupuestoSrvClient : System.ServiceModel.ClientBase<SistemaLiquidaciones.ProxyPresupuesto.IPresupuestoSrv>, SistemaLiquidaciones.ProxyPresupuesto.IPresupuestoSrv {
        
        public PresupuestoSrvClient() {
        }
        
        public PresupuestoSrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PresupuestoSrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PresupuestoSrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PresupuestoSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SistemaLiquidaciones.ProxyPresupuesto.PresupuestoBE[] ConsultarPresupuestoDispo(int CentroGestorId, int anho, string mes) {
            return base.Channel.ConsultarPresupuestoDispo(CentroGestorId, anho, mes);
        }
    }
}
