//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLiquidaciones.ProxyGasto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PresupuestoBE", Namespace="http://schemas.datacontract.org/2004/07/LiquidacionServices.BE")]
    [System.SerializableAttribute()]
    public partial class PresupuestoBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ANHOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CENTROGESTORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CENTROGESTORIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DETPRESUPUESTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EXCEDIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MONTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MONTODISPONIBLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MONTOEXCEDIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PARTIDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PARTIDAIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PRESUPUESTOIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ANHO {
            get {
                return this.ANHOField;
            }
            set {
                if ((this.ANHOField.Equals(value) != true)) {
                    this.ANHOField = value;
                    this.RaisePropertyChanged("ANHO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CENTROGESTOR {
            get {
                return this.CENTROGESTORField;
            }
            set {
                if ((object.ReferenceEquals(this.CENTROGESTORField, value) != true)) {
                    this.CENTROGESTORField = value;
                    this.RaisePropertyChanged("CENTROGESTOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CENTROGESTORID {
            get {
                return this.CENTROGESTORIDField;
            }
            set {
                if ((this.CENTROGESTORIDField.Equals(value) != true)) {
                    this.CENTROGESTORIDField = value;
                    this.RaisePropertyChanged("CENTROGESTORID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DETPRESUPUESTO {
            get {
                return this.DETPRESUPUESTOField;
            }
            set {
                if ((this.DETPRESUPUESTOField.Equals(value) != true)) {
                    this.DETPRESUPUESTOField = value;
                    this.RaisePropertyChanged("DETPRESUPUESTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EXCEDIDO {
            get {
                return this.EXCEDIDOField;
            }
            set {
                if ((this.EXCEDIDOField.Equals(value) != true)) {
                    this.EXCEDIDOField = value;
                    this.RaisePropertyChanged("EXCEDIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MES {
            get {
                return this.MESField;
            }
            set {
                if ((object.ReferenceEquals(this.MESField, value) != true)) {
                    this.MESField = value;
                    this.RaisePropertyChanged("MES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MONTO {
            get {
                return this.MONTOField;
            }
            set {
                if ((this.MONTOField.Equals(value) != true)) {
                    this.MONTOField = value;
                    this.RaisePropertyChanged("MONTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MONTODISPONIBLE {
            get {
                return this.MONTODISPONIBLEField;
            }
            set {
                if ((this.MONTODISPONIBLEField.Equals(value) != true)) {
                    this.MONTODISPONIBLEField = value;
                    this.RaisePropertyChanged("MONTODISPONIBLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MONTOEXCEDIDO {
            get {
                return this.MONTOEXCEDIDOField;
            }
            set {
                if ((this.MONTOEXCEDIDOField.Equals(value) != true)) {
                    this.MONTOEXCEDIDOField = value;
                    this.RaisePropertyChanged("MONTOEXCEDIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PARTIDA {
            get {
                return this.PARTIDAField;
            }
            set {
                if ((object.ReferenceEquals(this.PARTIDAField, value) != true)) {
                    this.PARTIDAField = value;
                    this.RaisePropertyChanged("PARTIDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PARTIDAID {
            get {
                return this.PARTIDAIDField;
            }
            set {
                if ((this.PARTIDAIDField.Equals(value) != true)) {
                    this.PARTIDAIDField = value;
                    this.RaisePropertyChanged("PARTIDAID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PRESUPUESTOID {
            get {
                return this.PRESUPUESTOIDField;
            }
            set {
                if ((this.PRESUPUESTOIDField.Equals(value) != true)) {
                    this.PRESUPUESTOIDField = value;
                    this.RaisePropertyChanged("PRESUPUESTOID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyGasto.IGastoSrv")]
    public interface IGastoSrv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGastoSrv/RegistrarGasto", ReplyAction="http://tempuri.org/IGastoSrv/RegistrarGastoResponse")]
        int RegistrarGasto(SistemaLiquidaciones.ProxyGasto.PresupuestoBE oPresupuestoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGastoSrv/ListarGastos", ReplyAction="http://tempuri.org/IGastoSrv/ListarGastosResponse")]
        SistemaLiquidaciones.ProxyGasto.PresupuestoBE[] ListarGastos(SistemaLiquidaciones.ProxyGasto.PresupuestoBE oPresupuestoBE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGastoSrv/EliminarGasto", ReplyAction="http://tempuri.org/IGastoSrv/EliminarGastoResponse")]
        int EliminarGasto(int detaPresupuestoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGastoSrv/ConsultarGastoExcedido", ReplyAction="http://tempuri.org/IGastoSrv/ConsultarGastoExcedidoResponse")]
        int ConsultarGastoExcedido(SistemaLiquidaciones.ProxyGasto.PresupuestoBE oPresupuestoBE);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGastoSrvChannel : SistemaLiquidaciones.ProxyGasto.IGastoSrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GastoSrvClient : System.ServiceModel.ClientBase<SistemaLiquidaciones.ProxyGasto.IGastoSrv>, SistemaLiquidaciones.ProxyGasto.IGastoSrv {
        
        public GastoSrvClient() {
        }
        
        public GastoSrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GastoSrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GastoSrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GastoSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RegistrarGasto(SistemaLiquidaciones.ProxyGasto.PresupuestoBE oPresupuestoBE) {
            return base.Channel.RegistrarGasto(oPresupuestoBE);
        }
        
        public SistemaLiquidaciones.ProxyGasto.PresupuestoBE[] ListarGastos(SistemaLiquidaciones.ProxyGasto.PresupuestoBE oPresupuestoBE) {
            return base.Channel.ListarGastos(oPresupuestoBE);
        }
        
        public int EliminarGasto(int detaPresupuestoId) {
            return base.Channel.EliminarGasto(detaPresupuestoId);
        }
        
        public int ConsultarGastoExcedido(SistemaLiquidaciones.ProxyGasto.PresupuestoBE oPresupuestoBE) {
            return base.Channel.ConsultarGastoExcedido(oPresupuestoBE);
        }
    }
}
