//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLiquidaciones.ProxyPartida {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartidaBE", Namespace="http://schemas.datacontract.org/2004/07/LiquidacionServices.BE")]
    [System.SerializableAttribute()]
    public partial class PartidaBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PARTIDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PARTIDAIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PARTIDA {
            get {
                return this.PARTIDAField;
            }
            set {
                if ((object.ReferenceEquals(this.PARTIDAField, value) != true)) {
                    this.PARTIDAField = value;
                    this.RaisePropertyChanged("PARTIDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PARTIDAID {
            get {
                return this.PARTIDAIDField;
            }
            set {
                if ((this.PARTIDAIDField.Equals(value) != true)) {
                    this.PARTIDAIDField = value;
                    this.RaisePropertyChanged("PARTIDAID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyPartida.IPartidaSrv")]
    public interface IPartidaSrv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPartidaSrv/ListarPartidas", ReplyAction="http://tempuri.org/IPartidaSrv/ListarPartidasResponse")]
        SistemaLiquidaciones.ProxyPartida.PartidaBE[] ListarPartidas(int CentroGestorId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPartidaSrvChannel : SistemaLiquidaciones.ProxyPartida.IPartidaSrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PartidaSrvClient : System.ServiceModel.ClientBase<SistemaLiquidaciones.ProxyPartida.IPartidaSrv>, SistemaLiquidaciones.ProxyPartida.IPartidaSrv {
        
        public PartidaSrvClient() {
        }
        
        public PartidaSrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PartidaSrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartidaSrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PartidaSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SistemaLiquidaciones.ProxyPartida.PartidaBE[] ListarPartidas(int CentroGestorId) {
            return base.Channel.ListarPartidas(CentroGestorId);
        }
    }
}
