//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaLiquidaciones.ProxyCentroGestor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CentroGestorBE", Namespace="http://schemas.datacontract.org/2004/07/LiquidacionServices.BE")]
    [System.SerializableAttribute()]
    public partial class CentroGestorBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CENTROGESTORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CENTROGESTORIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CENTROGESTOR {
            get {
                return this.CENTROGESTORField;
            }
            set {
                if ((object.ReferenceEquals(this.CENTROGESTORField, value) != true)) {
                    this.CENTROGESTORField = value;
                    this.RaisePropertyChanged("CENTROGESTOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CENTROGESTORID {
            get {
                return this.CENTROGESTORIDField;
            }
            set {
                if ((this.CENTROGESTORIDField.Equals(value) != true)) {
                    this.CENTROGESTORIDField = value;
                    this.RaisePropertyChanged("CENTROGESTORID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCentroGestor.ICentroGestorSrv")]
    public interface ICentroGestorSrv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentroGestorSrv/ListarCentroGestor", ReplyAction="http://tempuri.org/ICentroGestorSrv/ListarCentroGestorResponse")]
        SistemaLiquidaciones.ProxyCentroGestor.CentroGestorBE[] ListarCentroGestor();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICentroGestorSrvChannel : SistemaLiquidaciones.ProxyCentroGestor.ICentroGestorSrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CentroGestorSrvClient : System.ServiceModel.ClientBase<SistemaLiquidaciones.ProxyCentroGestor.ICentroGestorSrv>, SistemaLiquidaciones.ProxyCentroGestor.ICentroGestorSrv {
        
        public CentroGestorSrvClient() {
        }
        
        public CentroGestorSrvClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CentroGestorSrvClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentroGestorSrvClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentroGestorSrvClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SistemaLiquidaciones.ProxyCentroGestor.CentroGestorBE[] ListarCentroGestor() {
            return base.Channel.ListarCentroGestor();
        }
    }
}
